### ISSUE TITLE
On install : 'x86_64-linux-gnu-gcc' failed with exit status 4

### ISSUE THREAD

**Issue by Nico207** [bnjbvr/kresus#118]
Hello!

On a fresh install (Ubuntu server 14.04.2 up to date), when I try to activate Kresus i got this error:
> x86_64-linux-gnu-gcc: internal compiler error: Processus arrêté (program cc1)
> ...
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

Here is the full log

````
Is it installed?
=> No it isn't. Installing weboob...
[install.sh] -- New python executable in ./env/bin/python
Installing setuptools, pip...
[install.sh] -- done.
[install.sh] -- Downloading/unpacking git+git://git.symlink.me/pub/romain/weboob (from -r requirements.txt (line 1))
[install.sh] --   Cloning git://git.symlink.me/pub/romain/weboob to /tmp/pip-MnRUuD-build
[install.sh] --   Running setup.py (path:/tmp/pip-MnRUuD-build/setup.py) egg_info for package from git+git://git.symlink.me/pub/romain/weboob
[install.sh] --
[install.sh] -- Downloading/unpacking git+git://git.symlink.me/pub/weboob/modules (from -r requirements.txt (line 2))
[install.sh] --   Cloning git://git.symlink.me/pub/weboob/modules to /tmp/pip-Iucxm9-build
[install.sh] --   Running setup.py (path:/tmp/pip-Iucxm9-build/setup.py) egg_info for package from git+git://git.symlink.me/pub/weboob/modules
[install.sh] --
[install.sh] -- Downloading/unpacking cssselect (from -r requirements.txt (line 3))
[install.sh] --   Downloading cssselect-0.9.1.tar.gz
[install.sh] --   Running setup.py (path:/usr/local/cozy/apps/kresus/weboob/env/build/cssselect/setup.py) egg_info for package cssselect
[install.sh] --
[install.sh] --     no previously-included directories found matching 'docs/_build'
[install.sh] -- Downloading/unpacking lxml (from weboob==1.1->-r requirements.txt (line 1))
[install.sh] --   Running setup.py (path:/usr/local/cozy/apps/kresus/weboob/env/build/lxml/setup.py) egg_info for package lxml
[install.sh] --     /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
[install.sh] --     Building lxml version 3.4.4.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    
    warning: no previously-included files found matching '*.py'
[install.sh] -- Downloading/unpacking feedparser (from weboob==1.1->-r requirements.txt (line 1))
[install.sh] --   Running setup.py (path:/usr/local/cozy/apps/kresus/weboob/env/build/feedparser/setup.py) egg_info for package feedparser
[install.sh] --
[install.sh] -- Downloading/unpacking requests (from weboob==1.1->-r requirements.txt (line 1))
[install.sh] -- Downloading/unpacking python-dateutil (from weboob==1.1->-r requirements.txt (line 1))
[install.sh] -- Downloading/unpacking PyYAML (from weboob==1.1->-r requirements.txt (line 1))
[install.sh] --   Running setup.py (path:/usr/local/cozy/apps/kresus/weboob/env/build/PyYAML/setup.py) egg_info for package PyYAML
[install.sh] --
[install.sh] -- Downloading/unpacking prettytable (from weboob==1.1->-r requirements.txt (line 1))
[install.sh] --   Downloading prettytable-0.7.2.tar.bz2
[install.sh] --   Running setup.py (path:/usr/local/cozy/apps/kresus/weboob/env/build/prettytable/setup.py) egg_info for package prettytable
[install.sh] --
[install.sh] -- Downloading/unpacking Pillow (from weboob==1.1->-r requirements.txt (line 1))
[install.sh] --   Running setup.py (path:/usr/local/cozy/apps/kresus/weboob/env/build/Pillow/setup.py) egg_info for package Pillow
[install.sh] --     Single threaded build, not installing mp_compile: 1 processes
[install.sh] --
[install.sh] --     warning: no files found matching 'LICENSE' under directory 'docs'
[install.sh] -- Downloading/unpacking gdata (from weboob==1.1->-r requirements.txt (line 1))
[install.sh] --   Running setup.py (path:/usr/local/cozy/apps/kresus/weboob/env/build/gdata/setup.py) egg_info for package gdata
[install.sh] --
[install.sh] -- Downloading/unpacking mechanize (from weboob==1.1->-r requirements.txt (line 1))
[install.sh] --   Running setup.py (path:/usr/local/cozy/apps/kresus/weboob/env/build/mechanize/setup.py) egg_info for package mechanize
[install.sh] --
[install.sh] -- Downloading/unpacking futures (from weboob==1.1->-r requirements.txt (line 1))
[install.sh] --   Downloading futures-3.0.3-py2-none-any.whl
[install.sh] -- Downloading/unpacking six>=1.5 (from python-dateutil->weboob==1.1->-r requirements.txt (line 1))
[install.sh] --   Downloading six-1.9.0-py2.py3-none-any.whl
[install.sh] -- Installing collected packages: cssselect, lxml, feedparser, requests, python-dateutil, PyYAML, prettytable, Pillow, gdata, mechanize, futures, weboob, weboob-modules, six
[install.sh] --   Running setup.py install for cssselect
[install.sh] --
[install.sh] --     no previously-included directories found matching 'docs/_build'
[install.sh] --   Running setup.py install for lxml
[install.sh] --     /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
[install.sh] --     Building lxml version 3.4.4.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
[install.sh] --     building 'lxml.etree' extension
[install.sh] --     x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -I/usr/local/cozy/apps/kresus/weboob/env/build/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
[install.sh] --     x86_64-linux-gnu-gcc: internal compiler error: Processus arrêté (program cc1)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
[install.sh] --     error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
[install.sh] --     Complete output from command /usr/local/cozy/apps/kresus/weboob/env/bin/python -c "import setuptools, tokenize;__file__='/usr/local/cozy/apps/kresus/weboob/env/build/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-WLttZm-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/cozy/apps/kresus/weboob/env/include/site/python2.7:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'

  warnings.warn(msg)

Building lxml version 3.4.4.

Building without Cython.

Using build configuration of libxslt 1.1.28

running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/lxml

copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/sax.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/builder.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/__init__.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/cssselect.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml

creating build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-2.7/lxml/includes

creating build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/diff.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/clean.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/builder.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/defs.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml/html

creating build/lib.linux-x86_64-2.7/lxml/isoschematron

copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-2.7/lxml/isoschematron

copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-2.7/lxml/includes

creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources

creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng

copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng

creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl

copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl

copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl

creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

running build_ext

building 'lxml.etree' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/src

creating build/temp.linux-x86_64-2.7/src/lxml

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -I/usr/local/cozy/apps/kresus/weboob/env/build/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w

x86_64-linux-gnu-gcc: internal compiler error: Processus arrêté (program cc1)

Please submit a full bug report,

with preprocessed source if appropriate.

See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

----------------------------------------
[install.sh] -- Cleaning up...
[install.sh] -- Command /usr/local/cozy/apps/kresus/weboob/env/bin/python -c "import setuptools, tokenize;__file__='/usr/local/cozy/apps/kresus/weboob/env/build/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-WLttZm-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/cozy/apps/kresus/weboob/env/include/site/python2.7 failed with error code 1 in /usr/local/cozy/apps/kresus/weboob/env/build/lxml
[install.sh] stderr -- Traceback (most recent call last):
[install.sh] stderr --   File "/usr/local/cozy/apps/kresus/weboob/env/bin/pip", line 11, in <module>
[install.sh] stderr --
[install.sh] stderr -- sys.exit(main())
  File "/usr/local/cozy/apps/kresus/weboob/env/local/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/usr/local/cozy/apps/kresus/weboob/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 64: ordinal not in range(128)
````

**Comment by bnjbvr** [comment]
Thanks for reporting. The dependencies of Kresus include Weboob, which transitively include lxml, which needs to be compiled on your platform. However, if this is a compiler error, there's not much I can suggest, except for retrying, maybe? Or updating your build packages? If you're self-hosting and the device is low-end (e.g. raspberry pi with low memory), maybe the compiler is getting an out-of-memory exception, which will be hard to workaround.

**Comment by Nico207** [comment]
Yes!!! It's a memory exception...
I do my install on VirtualBox (1 CPU / 512Mb RAM). After upgrading the RAM to 1024, all work fine !
Thanks for your help.
