### ISSUE TITLE
Can't install Kresus anymore

### ISSUE THREAD

**Issue by frankrousseau** [bnjbvr/kresus#138]
Hi @bnjbvr,

  Since the new version I can't install Kresus anymore. I put the error stacktrace in the following. Do you have any idea of what's wrong?

```
[weboob] [install.sh] -- Collecting pycparser (from cffi>=0.8->cryptography>=0.7->pyopenssl->-r requirements.txt (line 4))
[weboob] [install.sh] --   Using cached pycparser-2.14.tar.gz
[weboob] [install.sh] -- Installing collected packages: pycparser, cffi, ipaddress, enum34, pyasn1, idna, cryptography, six, weboob-modules, weboob, futures, mechanize, gdata, Pillow, prettytable, PyYAML, python-dateutil, requests, feedparser, lxml, pyopenssl, cssselect
[weboob] [install.sh] --   Running setup.py install for pycparser
[weboob] [install.sh] --     Build the lexing/parsing tables
[weboob] [install.sh] --   Running setup.py install for cffi
[weboob] [install.sh] --     building '_cffi_backend' extension
[weboob] [install.sh] --     gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
[weboob] [install.sh] --     compilation terminated.
[weboob] [install.sh] --     error: command 'gcc' failed with exit status 1
[weboob] [install.sh] --     Complete output from command /usr/local/cozy/apps/kresus/weboob/env/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-9FwImv/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2z2vTq-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/cozy/apps/kresus/weboob/env/include/site/python2.7:
    running install
    
    running build
    
    running build_py
    
    creating build
    
    creating build/lib.linux-x86_64-2.7
    
    creating build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/recompiler.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/lock.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/verifier.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/cparser.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/gc_weakref.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/commontypes.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/api.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/__init__.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/model.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/_cffi_include.h -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/parse_c_type.h -> build/lib.linux-x86_64-2.7/cffi
    
    running build_ext
    
    building '_cffi_backend' extension
    
    creating build/temp.linux-x86_64-2.7
    
    creating build/temp.linux-x86_64-2.7/c
    
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
    
    compilation terminated.
    
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
[weboob] [install.sh] --     Command "/usr/local/cozy/apps/kresus/weboob/env/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-9FwImv/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2z2vTq-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/cozy/apps/kresus/weboob/env/include/site/python2.7" failed with error code 1 in /tmp/pip-build-9FwImv/cffi
[weboob] [install.sh] closed with code: 1
[weboob] error when installing/updating, attempt #3: return code of install.sh is 1, not 0.
[en] error when installing weboob: please contact a kresus maintainer on github or irc and keep the error message handy.
[fr] erreur lors de l'installation de weboob: merci de contacter un mainteneur de kresus sur github ou irc en gardant le message Ã  portÃ©e de main.
Fetch started: running process ./weboob/scripts/operations.sh...
weboob exited with code 1
weboob-stderr: Traceback (most recent call last):
  File "py/endpoint.py", line 1, in <module>
    from weboob.core.modules import ModuleLoadError
ImportError: No module named weboob.core.modules

when retrieving operations: Weboob error: Traceback (most recent call last):
  File "py/endpoint.py", line 1, in <module>
    from weboob.core.modules import ModuleLoadError
ImportError: No module named weboob.core.modules

rade): setuptools in ./env/lib/python2.7/site-packages (from cryptography>=0.7->pyopenssl->-r requirements.txt (line 4))
[weboob] [install.sh] -- Collecting enum34 (from cryptography>=0.7->pyopenssl->-r requirements.txt (line 4))
[weboob] [install.sh] --   Using cached enum34-1.0.4.tar.gz
[weboob] [install.sh] -- Collecting ipaddress (from cryptography>=0.7->pyopenssl->-r requirements.txt (line 4))
[weboob] [install.sh] --   Using cached ipaddress-1.0.14-py27-none-any.whl
[weboob] [install.sh] -- Collecting cffi>=0.8 (from cryptography>=0.7->pyopenssl->-r requirements.txt (line 4))
[weboob] [install.sh] --   Using cached cffi-1.1.2.tar.gz
[weboob] [install.sh] -- Collecting pycparser (from cffi>=0.8->cryptography>=0.7->pyopenssl->-r requirements.txt (line 4))
[weboob] [install.sh] --   Using cached pycparser-2.14.tar.gz
[weboob] [install.sh] -- Installing collected packages: pycparser, cffi, ipaddress, enum34, pyasn1, idna, cryptography, six, weboob-modules, weboob, futures, mechanize, gdata, Pillow, prettytable, PyYAML, python-dateutil, requests, feedparser, lxml, pyopenssl, cssselect
[weboob] [install.sh] --   Running setup.py install for pycparser
[weboob] [install.sh] --     Build the lexing/parsing tables
[weboob] [install.sh] --   Running setup.py install for cffi
[weboob] [install.sh] --     building '_cffi_backend' extension
[weboob] [install.sh] --     gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
[weboob] [install.sh] --     compilation terminated.
[weboob] [install.sh] --     error: command 'gcc' failed with exit status 1
[weboob] [install.sh] --     Complete output from command /usr/local/cozy/apps/kresus/weboob/env/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-9FwImv/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2z2vTq-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/cozy/apps/kresus/weboob/env/include/site/python2.7:
    running install
    
    running build
    
    running build_py
    
    creating build
    
    creating build/lib.linux-x86_64-2.7
    
    creating build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/recompiler.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/lock.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/verifier.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/cparser.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/gc_weakref.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/commontypes.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/api.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/__init__.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/model.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/_cffi_include.h -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/parse_c_type.h -> build/lib.linux-x86_64-2.7/cffi
    
    running build_ext
    
    building '_cffi_backend' extension
    
    creating build/temp.linux-x86_64-2.7
    
    creating build/temp.linux-x86_64-2.7/c
    
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
    
    compilation terminated.
    
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
[weboob] [install.sh] --     Command "/usr/local/cozy/apps/kresus/weboob/env/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-9FwImv/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2z2vTq-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/cozy/apps/kresus/weboob/env/include/site/python2.7" failed with error code 1 in /tmp/pip-build-9FwImv/cffi
[weboob] [install.sh] closed with code: 1
[weboob] error when installing/updating, attempt #3: return code of install.sh is 1, not 0.
[en] error when installing weboob: please contact a kresus maintainer on github or irc and keep the error message handy.
[fr] erreur lors de l'installation de weboob: merci de contacter un mainteneur de kresus sur github ou irc en gardant le message Ã  portÃ©e de main.
Fetch started: running process ./weboob/scripts/operations.sh...
weboob exited with code 1
weboob-stderr: Traceback (most recent call last):
  File "py/endpoint.py", line 1, in <module>
    from weboob.core.modules import ModuleLoadError
ImportError: No module named weboob.core.modules

when retrieving operations: Weboob error: Traceback (most recent call last):
  File "py/endpoint.py", line 1, in <module>
    from weboob.core.modules import ModuleLoadError
```

**Comment by ZeHiro** [comment]
Hi @frankrousseau 
IT seems new package dependencied (system wide) are needed, see : 

https://github.com/bnjbvr/kresus/issues/134

**Comment by bnjbvr** [comment]
Thanks @frankrousseau for the report and @ZeHiro for the help. Indeed, it seems `libffi-dev` is missing. I am closing the issue, assuming nothing else went bad.
