### ISSUE TITLE
"xhr error: Internal Server Error" when updating BNP account

### ISSUE THREAD

**Issue by nicodel** [bnjbvr/kresus#146]
Hi,

Cozy instance hosted on Cozy infrastructure
Data System: 2.0.6
Proxy: 2.1.0
Home: 2.0.6
Controller: 2.0.29
Kresus -  0.5.2

Since the 25/07 automatic sync of my BNP accounts is not done and when I press "Synchroniez now" I get a popup windows the following message:
```
xhr error: Internal Server Error
Weboob error when importing operations:
when retrieving operations: Weboob error: Traceback (most recent call last):
  File "py/endpoint.py", line 111, in <module>
    content = BankHistoryHandler(id, password, website).post(bankuuid)
  File "py/endpoint.py", line 84, in post
    return self.load_from_connector(name)
  File "py/endpoint.py", line 46, in load_from_connector
    raise Exception("Unexpected Weboob error: %s" % unicode(e))
Exception: Unexpected Weboob error: 
```

The Kresus logs look like this:
```
Checking new operations for all bank accesses...
Success: All banks added.
Error when polling accounts: when retrieving operations: Weboob error: Traceback (most recent call last):
  File "py/endpoint.py", line 111, in <module>
    content = BankHistoryHandler(id, password, website).post(bankuuid)
  File "py/endpoint.py", line 84, in post
    return self.load_from_connector(name)
  File "py/endpoint.py", line 46, in load_from_connector
    raise Exception("Unexpected Weboob error: %s" % unicode(e))
Exception: Unexpected Weboob error: Backend(bnporc): Configuration error for field "password": Value "undefined" does not match regexp "^(\d{6}|)$"

weboob exited with code 1
weboob-stderr: Traceback (most recent call last):
  File "py/endpoint.py", line 111, in <module>
    content = BankHistoryHandler(id, password, website).post(bankuuid)
  File "py/endpoint.py", line 84, in post
    return self.load_from_connector(name)
  File "py/endpoint.py", line 46, in load_from_connector
    raise Exception("Unexpected Weboob error: %s" % unicode(e))
Exception: Unexpected Weboob error: Backend(bnporc): Configuration error for field "password": Value "undefined" does not match regexp "^(\d{6}|)$"

when retrieving operations: Weboob error: Traceback (most recent call last):
  File "py/endpoint.py", line 111, in <module>
    content = BankHistoryHandler(id, password, website).post(bankuuid)
  File "py/endpoint.py", line 84, in post
    return self.load_from_connector(name)
  File "py/endpoint.py", line 46, in load_from_connector
    raise Exception("Unexpected Weboob error: %s" % unicode(e))
Exception: Unexpected Weboob error: Backend(bnporc): Configuration error for field "password": Value "undefined" does not match regexp "^(\d{6}|)$"
```

**Comment by bnjbvr** [comment]
Thanks for the report. It seems that either your password has somehow be cleared from the database, or the Weboob module is no longer working. Can you try:

1) Update your bank password in the Kresus interface (in the Settings, list of banks, there's a button to update a bank link).
2) Update weboob (in the Settings, Advanced tab, click "reinstall weboob" and wait a few minutes)

Hope that helps.

**Comment by nicodel** [comment]
Thanks @bnjbvr 
Solution 1 worked fine.
