### ISSUE TITLE
undefined property in alert-manager.js

### ISSUE THREAD

**Issue by nicofrand** [bnjbvr/kresus#162]
I do not know the context (probably when starting kresus), but I have some weird things in my log:

```console
Fetch started: running process ./weboob/scripts/operations.sh...
weboob exited with code 0
weboob-stderr: undefined
weboob exited normally with non-empty JSON content, continuing.

TypeError: Cannot read property 'length' of undefined
    at /usr/local/cozy/apps/kresus/build/server/lib/alert-manager.js:60:39
    at /usr/local/cozy/apps/kresus/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/lib/cozy_data_system.js:522:20
    at parseBody (/usr/local/cozy/apps/kresus/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/node_modules/request-json/main.js:26:12)
    at Request._callback (/usr/local/cozy/apps/kresus/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/node_modules/request-json/main.js:81:18)
    at Request.self.callback (/usr/local/cozy/apps/kresus/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/node_modules/request-json/node_modules/request/index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/cozy/apps/kresus/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/node_modules/request-json/node_modules/request/index.js:876:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/kresus/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/node_modules/request-json/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:117:20)
```

**Comment by bnjbvr** [comment]
Thank you for the report. Looks like there are missing checks that `alerts` is defined.
