### ISSUE TITLE
kresus doesn't start when hostname can't be resolved

### ISSUE THREAD

**Issue by fcrozat** [bnjbvr/kresus#206]
If system hostname isn't resolvable (for instance hostname returns foobar), kresus (in standalone mode) will fail to start : 
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: getaddrinfo ENOTFOUND foobar
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)

You need to start it with HOST=localhost

It might be better to hardcode that in kresus code, when being started in standalone mode.

**Comment by bnjbvr** [comment]
Thanks for the report! However, Kresus uses the HOST env variable, so if it's set to something weird, that's going to be used.

Maybe I could add command line options when starting the Kresus program, such as the port / host variable, etc. Would that help?

**Comment by fcrozat** [comment]
on a linux distro (at least on openSUSE), HOST will be set to $(uname -n). But a lot of systems (mine included) might have a non-resolvable hostname. First, I would suggest to document in the readme the usage of HOST environment variable, in addition to PORT (I saw a pending fix for this one). I'm not sure if HOST=localhost should be forced to user.

Or maybe if we can change de default hostname and port in a config file used by "node bin/kresus.js", that could be enough..

**Comment by bnjbvr** [comment]
Good call on the README, I'll add this before the next release.

Having a `.kresus.rc` sounds appealing, but I wonder whether passing command line options wouldn't be simpler? I'll definitely try a few things.
