### ISSUE TITLE
When no accounts are configured, redirect to the "create bank access" page

### ISSUE THREAD

**Issue by jankeromnes** [bnjbvr/kresus#25]
1. Install Kresus
2. Click on "(sync now)"
3. This happens:

    Assertion error: 
    Error
    at exports.assert (https://localhost:2223/apps/kresus/js/main.js:32:64)
    at EventEmitter.store.fetchOperations (https://localhost:2223/apps/kresus/js/main.js:1663:5)
    at Object.ID_1 (https://localhost:2223/apps/kresus/js/main.js:1815:15)
    at Dispatcher.$Dispatcher_invokeCallback (https://localhost:2223/apps/kresus/js/main.js:1354:35)
    at Dispatcher.dispatch (https://localhost:2223/apps/kresus/js/main.js:1329:14)
    at module.exports.React.createClass.onFetchOperations_ (https://localhost:2223/apps/kresus/js/main.js:907:14)
    at boundMethod (https://localhost:2223/apps/kresus/js/vendor/react.js:6644:21)
    at Object.executeDispatch (https://localhost:2223/apps/kresus/js/vendor/react.js:3181:21)
    at SimpleEventPlugin.executeDispatch (https://localhost:2223/apps/kresus/js/vendor/react.js:14331:40)
    at forEachEventDispatch (https://localhost:2223/apps/kresus/js/vendor/react.js:3169:5)

**Comment by jankeromnes** [comment]
Actually looks like

    Uncaught TypeError: Cannot read property 'id' of null

in main.js, where `currentAccount` is undefined (because I haven't added accounts yet):

    store.fetchOperations = function() {
        assert(this.currentAccount !== null);
        $.get('accounts/retrieveOperations/' + this.currentAccount.id, function (data) {
            store.currentAccount = new Account(data);
            store.loadOperationsFor(store.currentAccount);
        }).fail(xhrError);
    };

**Comment by bnjbvr** [comment]
Bad error message for saying "This app cannot currently allow you to add / delete accounts. You need to use cozy-pfm to do this." See also issue #12

**Comment by jankeromnes** [comment]
To be honest, by clicking on "sync" with no account yet, I was half-expecting something might break :)

**Comment by bnjbvr** [comment]
Changing title to better reflect the issue. Depends on #12.
