### ISSUE TITLE
Pb during Kresus clean installation

### ISSUE THREAD

**Issue by eravion** [bnjbvr/kresus#285]
[2015-11-19 15:56:27:743] info - sources/weboob | install.sh stdout -- Downloading/unpacking ipaddress (from cryptography>=0.7->pyopenssl->-r requirements.txt (line 4))

[2015-11-19 15:56:27:970] info - sources/weboob | install.sh stdout --   Downloading ipaddress-1.0.15-py27-none-any.whl

[2015-11-19 15:56:27:979] info - sources/weboob | install.sh stdout -- Downloading/unpacking cffi>=1.1.0 (from cryptography>=0.7->pyopenssl->-r requirements.txt (line 4))

[2015-11-19 15:56:29:113] info - sources/weboob | install.sh stdout --   Running setup.py (path:/tmp/pip-build-p_f0xl/cffi/setup.py) egg_info for package cffi

[2015-11-19 15:56:29:270] info - sources/weboob | install.sh stdout --     

[2015-11-19 15:56:29:309] info - sources/weboob | install.sh stdout -- Downloading/unpacking pycparser (from cffi>=1.1.0->cryptography>=0.7->pyopenssl->-r requirements.txt (line 4))

[2015-11-19 15:56:29:948] info - sources/weboob | install.sh stdout --   Running setup.py (path:/tmp/pip-build-p_f0xl/pycparser/setup.py) egg_info for package pycparser

[2015-11-19 15:56:30:49] info - sources/weboob | install.sh stdout --     

[2015-11-19 15:56:30:68] info - sources/weboob | install.sh stdout --     warning: no previously-included files matching 'yacctab.*' found under directory 'tests'

[2015-11-19 15:56:30:69] info - sources/weboob | install.sh stdout --     warning: no previously-included files matching 'lextab.*' found under directory 'tests'

[2015-11-19 15:56:30:70] info - sources/weboob | install.sh stdout --     warning: no previously-included files matching 'yacctab.*' found under directory 'examples'

[2015-11-19 15:56:30:71] info - sources/weboob | install.sh stdout --     warning: no previously-included files matching 'lextab.*' found under directory 'examples'

[2015-11-19 15:56:30:89] info - sources/weboob | install.sh stdout -- Installing collected packages: cssselect, pyopenssl, pyexecjs, lxml, feedparser, requests, python-dateutil, PyYAML, prettytable, Pillow, gdata, mechanize, futures, weboob, weboob-modules, six, cryptography, idna, pyasn1, enum34, ipaddress, cffi, pycparser

[2015-11-19 15:56:30:90] info - sources/weboob | install.sh stdout --   Running setup.py install for cssselect

[2015-11-19 15:56:30:226] info - sources/weboob | install.sh stdout --     

[2015-11-19 15:56:30:240] info - sources/weboob | install.sh stdout --     no previously-included directories found matching 'docs/_build'

[2015-11-19 15:56:30:354] info - sources/weboob | install.sh stdout --   Running setup.py install for pyexecjs

[2015-11-19 15:56:30:461] info - sources/weboob | install.sh stdout --     

[2015-11-19 15:56:30:508] info - sources/weboob | install.sh stdout --   Running setup.py install for lxml

[2015-11-19 15:56:30:626] info - sources/weboob | install.sh stdout --     Building lxml version 3.5.0.

[2015-11-19 15:56:30:626] info - sources/weboob | install.sh stdout --     Building without Cython.
    Using build configuration of libxslt 1.1.28

[2015-11-19 15:56:30:644] info - sources/weboob | install.sh stdout --     building 'lxml.etree' extension

[2015-11-19 15:56:30:645] info - sources/weboob | install.sh stdout --     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/libxml2 -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w

[2015-11-19 15:56:57:547] warn - sources/weboob | test install stdout: 
test install stderr: Traceback (most recent call last):

  File "<string>", line 1, in <module>

ImportError
: 
No module named weboob.core

Traceback (most recent call last):

  File "<string>", line 1, in <module>

ImportError
: 
No module named weboob.core

[2015-11-19 15:56:57:547] warn - sources/weboob | test install stdout: 
test install stderr: Traceback (most recent call last):

  File "<string>", line 1, in <module>

ImportError
: 
No module named weboob.core

Traceback (most recent call last):

  File "<string>", line 1, in <module>

ImportError
: 
No module named weboob.core

**Comment by bnjbvr** [comment]
@eravion, was it solved by installing the dependencies, as explained on https://github.com/bnjbvr/kresus#on-any-other-unix-based-operating-system ?

**Comment by eravion** [comment]
Hi,

Yes, thanks :)
