### ISSUE TITLE
"unexpected error: undefined" when adding account

### ISSUE THREAD

**Issue by peshane** [bnjbvr/kresus#340]
Hi,

Just trying cozy cloud and I'm really interested by kresus :)

Sadly, when I try to add my bank account I've got an "unexpected error: undefined" message box. In the kresus-err.log I've got this:
```
[2016-02-01 15:46:21:76] error - helpers | Error: when creating a bank access: no bodyerror:   File "py/endpoint.py", line 136
    print json.dumps(content, ensure_ascii=False).encode('utf-8')
             ^
SyntaxError: invalid syntax
 - when creating a bank access: Internal server error
```

It's seem that I've got this for all bank possible except the fakes one.

I also try with a packaged weboob installation, which works well on with it's own cli interface but kresus doesn't look like trying to use this, but I'm not sure about that.

I'm on archlinux with python 3.5 and cozy was installed by the "cozy-apache" AUR's package.

Any help would be appreciate :)

**Comment by bnjbvr** [comment]
Hi! Thanks for opening an issue about this. So far, and it should be more explicit in the README I guess, Kresus only works with python2. The scripts in `weboob/scripts` could probably be tweaked to reflect this more. If you have some knowledge about python2/python3, can you try fixing the code there, please? Otherwise, ping @babolivier who might be interested in this and more helpful than I am :-).

Note that on the development branch `incoming`, the code has changed enough that all python code is only within a single file, `server/weboob/main.py`.

**Comment by peshane** [comment]
just find a way to tell kresus to use python2 when installing weboob :)

in weboob/scripts/install.sh, line 7, just swapping the "which" order for having "virtualenv2" first:
`pyvenv=$(which virtualenv2 || which virtualenv || echo "") ` 

after this, reinstalling weboob from the kresus's interface and it'w working :)

**Comment by babolivier** [comment]
I started working on a fix in #272, was supposed to optimize it but no time.

@peshane Indeed this order makes more sense, I don't know why I didn't do it like this :)

Can't promise to work on a PR this week, even though I'd like to, so feel free to submit a fix if you want.

**Comment by peshane** [comment]
well, first time on github so may be i've mistaken, but the fix is here: [https://github.com/babolivier/kresus/commit/908c774fe4987d0e48080c054d65bd3dfd8b947a](url)

**Comment by bnjbvr** [comment]
Cheers! Looks like the right fix, but the code as changed much on the dev branch. Now there's only one python script, that's called by dashbang:

https://github.com/bnjbvr/kresus/blob/incoming/server/weboob/main.py#L1
https://github.com/bnjbvr/kresus/blob/incoming/server/lib/sources/weboob.js#L17

How could we adapt this fix to the dev version?

**Comment by peshane** [comment]
maybe use this shebang:
`#!/usr/bin/env python2`

must be ok for rhel/centos/fedora like distribution, I assume others to

**Comment by nikaro** [comment]
Hello,

I have the same error message when I try to add an account. But my installation and the error log are different.

I have done Debian standalone installation. And the error raised in the log is :
```
[2016-02-02 10:58:51:885] info - sources/weboob | stderr: Traceback (most recent call last):
  File "py/endpoint.py", line 10, in <module>
    with file('../shared/errors.json') as f:
IOError: [Errno 2] No such file or directory: '../shared/errors.json'

[2016-02-02 10:58:51:887] error - controllers/accesses | The access process creation failed, cleaning up...
[2016-02-02 10:58:51:887] info - controllers/accesses | 	deleting access...
[2016-02-02 10:58:51:892] warn - helpers | no status in asyncErr
[2016-02-02 10:58:51:892] warn - helpers | no error message in asyncErr
[2016-02-02 10:58:51:892] error - helpers | Error: when creating a bank access: no bodyerror: Traceback (most recent call last):
  File "py/endpoint.py", line 10, in <module>
    with file('../shared/errors.json') as f:
IOError: [Errno 2] No such file or directory: '../shared/errors.json'
 - when creating a bank access: Internal server error
[Tue, 02 Feb 2016 10:17:04 GMT] - POST /accesses/ - 500 - 389.626 ms -  64
```

The file `../shared/errors.json` exists in the directory where i cloned the repo, but not in `~/.kresus` from where the application seems to run.

I solved my issue by clone the repo in `~/.kresus`.

**Comment by bnjbvr** [comment]
Hi Nikaro,

Thank you for the report. I've dramatically changed how weboob is called in the next version and so this shouldn't happen again. Your workaround of cloning the repo in ~/.kresus is correct, in the meanwhile. I will let this issue open until we release the next version, to get feedback from you all.

Cheers!
