### ISSUE TITLE
"xhr error: error Internal Server Error" when try to add a CIC bank account

### ISSUE THREAD

**Issue by nledez** [bnjbvr/kresus#42]
Hi @bnjbvr,

I try to add a CIC bank account (with FF on Mac OS X).

But I have an error in my browser:
```
xhr error: error
Internal Server Error
```

And on my server I have:
```
[2015-03-16 09:30:36:680] error - app:error | Parsing error : Unexpected token T, body=
 Traceback (most recent call last):
  File "/usr/local/cozy-indexer/cozy-data-indexer/virtualenv/local/lib/python2.7/site-packages/tornado/web.py", line 1042, in _execute
    getattr(self, self.request.method.lower())(*args, **kwargs)
  File "/usr/local/cozy-indexer/cozy-data-indexer/handlers/connectors.py", line 68, in post
    self.return_json(self.load_from_connector(name, 'get_balances'))
  File "/usr/local/cozy-indexer/cozy-data-indexer/handlers/connectors.py", line 49, in load_from_connector
    self.raise_error("Something went wrong (weboob modules should "
  File "/usr/local/cozy-indexer/cozy-data-indexer/handlers/base.py", line 62, in raise_error
    raise tornado.web.HTTPError(status_code, msg)
HTTPError: HTTP 400: Bad Request (Something went wrong (weboob modules should probably be updated))
```

Thanks for your great app :)

**Comment by adeleglise** [comment]
Bonjour, même erreur pour moi en essayant d'ajouter un compte Banque Populaire (je suis à la Banque Populaire du Nord) 

Logs : 
[E 150316 11:27:44 web:1085] Uncaught exception POST /connectors/bank/banquepopulaire/ (127.0.0.1)
    HTTPRequest(protocol='http', host='localhost:9102', method='POST', uri='/connectors/bank/banquepopulaire/', version='HTTP/1.1', remote_ip='127.0.0.1', body='{"login":"XXXXXX","password":"XXXXXX"}', headers={'Content-Length': '44', 'Host': 'localhost:9102', 'Content-Type': 'application/json', 'Connection': 'keep-alive', 'Accept': 'application/json', 'User-Agent': 'request-json/1.0'})
    Traceback (most recent call last):
      File "/usr/local/cozy-indexer/cozy-data-indexer/virtualenv/lib/python2.6/site-packages/tornado/web.py", line 1042, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/usr/local/cozy-indexer/cozy-data-indexer/handlers/connectors.py", line 52, in post
        self.return_json(self.load_from_connector(name, 'get_balances'))
      File "/usr/local/cozy-indexer/cozy-data-indexer/handlers/connectors.py", line 27, in load_from_connector
        connector = Connector(name, {'login': login, 'password': password})
      File "/usr/local/cozy-indexer/cozy-data-indexer/lib/connector.py", line 22, in __init__
        self.backend = weboob.build_backend(connector, parameters)
      File "/usr/local/cozy-indexer/cozy-data-indexer/virtualenv/lib/python2.6/site-packages/weboob/core/ouiboube.py", line 104, in build_backend
        backend_instance = module.create_instance(self, name or module_name, params or {}, storage)
      File "/usr/local/cozy-indexer/cozy-data-indexer/virtualenv/lib/python2.6/site-packages/weboob/core/modules.py", line 97, in create_instance
        backend_instance = self.klass(weboob, instance_name, config, storage, self.logger)
      File "/usr/local/cozy-indexer/cozy-data-indexer/virtualenv/lib/python2.6/site-packages/weboob/tools/backend.py", line 276, in __init__
        self.config = self.CONFIG.load(weboob, self.NAME, self.name, config)
      File "/usr/local/cozy-indexer/cozy-data-indexer/virtualenv/lib/python2.6/site-packages/weboob/tools/backend.py", line 160, in load
        % (cfg.instname, name, field.description))
    ConfigError: Backend(banquepopulaire): Configuration error: Missing parameter "website" (R\xe9gion)

**Comment by bnjbvr** [comment]
Meh, actually comment 1 and 2 were not about the same issue. Reopening for comment 1.

**Comment by adeleglise** [comment]
Bonjour,

suite au commit, je vois bien le menu droulant pour selectionner la région, mais la même erreur se reproduit, voici le log de kresus :

 304 - - 11 ms
127.0.0.1 - GET /categories HTTP/1.1 304 - - 7 ms
127.0.0.1 - GET /banks?withAccountOnly=true HTTP/1.1 304 - - 14 ms
Weboob is not available -- null
127.0.0.1 - POST /accesses/ HTTP/1.1 500 34 - 24 ms
Error -  when loading accounts for the first time: Weboob is not available -- null

**Comment by adeleglise** [comment]
Bonjour,

j'ai désinstaller kresus, puis réinstaller à partir du lien github et maintenant je ne peux plus synchronisé les informations de mon compte.
J'ai toujours des informations de 2014 affichées.

**Comment by bnjbvr** [comment]
Hey, can you guys try again with the latest master version? (which is the one proposed by default in cozy, so no more trick with the URL)

**Comment by bnjbvr** [comment]
@nledez , can you update Kresus to the latest version and try again, please? (and close the issue if it doesn't happen anymore)

**Comment by nledez** [comment]
Work fine thanks!

**Comment by adeleglise** [comment]
Works fine too, but I've opened a new issue, as old data appears in the app.
