### ISSUE TITLE
Problem when updating Kresus

### ISSUE THREAD

**Issue by lutcheti** [bnjbvr/kresus#52]
Thanks again for the good work ;)

It seems that Kresus failed to update:
```log
Is it installed?
Installing...
[install.sh] stderr -- mkdir: 
[install.sh] stderr -- cannot create directory `env'
[install.sh] stderr -- : Permission denied
[install.sh] stderr -- 

[install.sh] stderr -- Traceback (most recent call last):

[install.sh] stderr --   File "/usr/local/bin/virtualenv", line 11, in <module>

[install.sh] stderr --     
[install.sh] stderr -- sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 825, in main

[install.sh] stderr --     symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 985, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1159, in install_python
    mkdir(lib_dir)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 448, in mkdir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: 'env'

[install.sh] stderr -- ./weboob/install.sh: line 7: env/bin/activate: No such file or directory

[install.sh] closed with code: 1
[en] error when installing weboob: please contact a kresus maintainer on github or irc and keep the error message handy.
[fr] erreur lors de l'installation de weboob: merci de contacter un mainteneur de kresus sur github ou irc en gardant le message à portée de main.
```

**Comment by lutcheti** [comment]
Solved after removed and re-installed Kresus.

**Comment by bnjbvr** [comment]
Thanks! I will try to update the first install, so that it retries installing in case something went wrong...
